isim="Solmaz"
print(isim[0])#S
print(isim[1])#o
print(isim[2])#l
print(isim[3])#m
print(isim[4])#a
print(isim[5])#z
isim="Solmaz"
print(isim[-6])#s
print(isim[-1])#o
print(isim[-4])#l
print(isim[-3])#m
print(isim[-2])#a
print(isim[-1])#z